### ISSUE TITLE
Feature Request: do not load image if parent container is in display:none mode.

### ISSUE THREAD

**Issue by fliespl** [cdowdy/io-lazyload#12]
That happens when you have container (i.e. read more) that unveils content on click.

Right now - image would be loaded. Even though it's not visible due to being hidden within parent.

Sample code:
```
<div class="show_more"><a class="show-more"> Read more …</a> -> clicking makes next div visible
<div class="content-hide">
// image here
</div></div>
```

**Comment by cdowdy** [comment]
I don't know how you're toggling the visibility (edit: im a dunce you said display:none right in the title lol)  of your div you have in your example (``.content-hide``) or the image element but since intersection observer deals with the actual visibility of the target it will in this case download the image if its visible to the document. 

You could rectify this by some CSS (again depending on how you're toggling the visibility) or with some javascript. 

Here is a quick example using the io-lazyload demo page and toggling the element with Javascript and having the atttribute "hidden" on the image element from the start:  

```css  
/* this is the only additional bit of CSS I added to the demo page /*  

.content-hide {
  visibility: hidden;
}
```

```HTML  
<div class="image-box">
    <button class="show-more"> Show Image:</button>
    <div class="content-hide">
        <img id="one" 
            hidden 
            sizes="(min-width: 530px) 25vw, 100vw"
            data-srcset="img-177w.png 177w,
                img-240w.png 240w,
                img-321w.png 321w,
                img-640-th.png 367w"
            data-src="img-640-th.png"
            alt=""
            class="lazyload"
            width="100%">
    </div>
</div>
``` 
when the button is clicked we remove the ```.content-hide``` class (or you could overwrite a single attribute) and remove the hidden attribute from the image. Now this isn't a very robust example but I wanted to show it:  


```Javascript
    const button = document.querySelector('.show-more');
    button.addEventListener('click', () => {
        let show = document.querySelector('.content-hide');
        let image = show.querySelector('.lazyload')
        // use inline styles or classList
        // show.classList.remove('content-hide');
        // show.classList.toggle('class-to-add-or-remove');
        show.style.visibility = 'visible';
        image.removeAttribute('hidden');
    });
```

![2020-12-08_12-54-04](https://user-images.githubusercontent.com/5969974/101525879-e8784200-3959-11eb-9e89-2d61fe3b2f8c.gif)

since this, in my opinion, isn't something directly related to this library I'm gonna close this but please feel free to come and comment back if you A) don't feel that way :) or B) need some help getting your image download issue squared away!

**Comment by fliespl** [comment]
Hi Cory,
first of all - thank you for your reply.

During my tests I have figured that adding:
t.isIntersecting && **t.target.offsetParent !== null** while doing check next to isIntersecting did the trick to me.

Not sure if it's viable solution to the library, but still sharing it. Like the idea of "hidden" attribute - I have thought it was not supported in all browsers, but once I checked it today it seems to break only on IE 10 (which is a minor issue at this moment).
